language: node_js
node_js:
  - "4"
  - "5"
  - "6"
env:
  - WEBPACK_VERSION=1 EXTRACT_TEXT_VERSION=$WEBPACK_VERSION
  - WEBPACK_VERSION=2 EXTRACT_TEXT_VERSION=$WEBPACK_VERSION
  - WEBPACK_VERSION=3 EXTRACT_TEXT_VERSION=^2.1.2
before_install:
  - stty columns 120
install:
  - npm install --ignore-scripts
  - npm rm webpack
  - npm rm extract-text-webpack-plugin
  - npm install webpack@$WEBPACK_VERSION --ignore-scripts || true
  - npm install extract-text-webpack-plugin@$EXTRACT_TEXT_VERSION --ignore-scripts || true
script:
  - npm test
