language: node_js
node_js:
  - "4"
  - "5"
  - "6"
env:
  - WEBPACK_VERSION=1
  - WEBPACK_VERSION=2
  - WEBPACK_VERSION=3
before_install:
  - stty columns 120
install:
  - npm install --ignore-scripts
  - npm rm webpack
  - npm rm extract-text-webpack-plugin
  - npm install webpack@$WEBPACK_VERSION extract-text-webpack-plugin@$WEBPACK_VERSION --ignore-scripts || true
script:
  - npm test
